---
title: "R Notebook"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, 1_clean_all_data}
library(FNN)
library(XML)
library(tidyverse)
library(ggfortify)
library(ggplot2)

rm(list = ls())

get_subject_order_map <- function() {
  subject_order_map <- read.table("order_arrange")
  subject_order_map + 1
}

get_map_score <- function() {
  if (str_detect(Sys.info()['sysname'], "Darwin")) {
    path_data <- "resource/res_analyz_spr_10/"
  } else {
    path_data <- "E:\\baiduyun\\github\\tsp_experiment\\tsp_experiment\\resource\\res_analyz_spr_10"
  }
  best_value <- as.numeric(readLines(file.path(path_data,"ColorOptimalLength.txt"), 30))
  best_value
}

# 32 subjects
get_subject_dir_map <- function() {
  if (str_detect(Sys.info()['sysname'], "Darwin")) {
    path_data <- "resource/res_analyz_spr_10/TSP_spr_19/colored"
  } else {
    path_data <- "E:\\baiduyun\\github\\tsp_experiment\\tsp_experiment\\resource\\res_analyz_spr_10\\TSP_spr_19/colored"
  }

  dirsAll <- list.dirs(path =file.path(path_data) , full.names = TRUE, recursive = TRUE) 
  dirsAll <- grep("results", dirsAll, value = TRUE)
  subj_count <- length(dirsAll) #
  dirsAll
}

get_distance_from_two_record <- function(point1, point2) {
  distance <- sqrt((point1-point2)[1]^2 + (point1-point2)[2]^2)
  if(point1[3] != point2[3]) {
      distance <- 2 * distance
  }
  distance
}

get_file_content <- function(map_id, subject_id, subject_dir_map) {
  if (str_detect(Sys.info()['sysname'], "Darwin")) {
    file <- paste(subject_dir_map[subject_id],"/TSPMap_RandomPoints_Color_SwitchCost_", toString(map_id-1),"-CollectedTour.tspx",sep = "")
  } else {
    file <- paste(subject_dir_map[subject_id],"\\TSPMap_RandomPoints_Color_SwitchCost_", toString(map_id-1),"-CollectedTour.tspx",sep = "")
  }

  file_content = readChar(file, file.info(file)$size)
  file_content
}

get_real_record_distance <- function(map_id, subject_id, subject_dir_map) {
  file_content = get_file_content(map_id, subject_id, subject_dir_map)
  
  if (0 == length(file_content)) {
    warning("There are empty file, should check!")
  }
  
  tmp_data <- NULL
  first_data <- NULL
  distance_all <- 0
  count <- 0
  for(city in xmlChildren(xmlChildren(xmlChildren(xmlRoot(xmlParse(file_content)))$Tours)$Tour)) {
    count <- count + 1
    
    data<-c(as.numeric(xmlAttrs(city)['x']), as.numeric(xmlAttrs(city)['y']), as.numeric(xmlAttrs(city)['group']))
    
    if(is.null(first_data)) { first_data <- data; }

    if (count != 1) {
      distance_all <- distance_all + get_distance_from_two_record(tmp_data, data)
      if (count == 50) {
        distance_all <- distance_all + get_distance_from_two_record(first_data, data)
      }
    }
    tmp_data <- data
  }

  distance_all
}

map_score <- get_map_score()
subject_dir_map <- get_subject_dir_map()
subject_order_map <- get_subject_order_map()

experiment_table <- data.frame()

for(subject_id in 1:30) {
  for(map_id in 1:30) {
    real_score <- get_real_record_distance(map_id, subject_id, subject_dir_map)
    best_score <- map_score[map_id]
    err_ratio <- (real_score-best_score)/best_score
    order_1_to_30 <- subject_order_map[subject_id, map_id]
    block_1_to_6 <- floor((order_1_to_30 - 1) / 5) + 1
    record <- data.frame(map_id, subject_id, real_score, best_score, err_ratio, order_1_to_30, block_1_to_6)
    experiment_table <- rbind(experiment_table, record)
  }
}
experiment_table
# That is what we need for next step!!
#experiment_table

# write.csv(experiment_table, file='resource/experiment_table.csv', row.names = FALSE)
```

```{r plot_the_trace}
get_experiment_coord <- function(map_id, subject_id, subject_dir_map) {
  file_content = get_file_content(map_id, subject_id, subject_dir_map)
  if (0 == length(file_content)) {
    warning("There are empty file, should check!")
  }
  coord <- data.frame()
  count <- 0
  for(city in xmlChildren(xmlChildren(xmlChildren(xmlRoot(xmlParse(file_content)))$Tours)$Tour)) {
    count <- count + 1
    data<-c(map_id, subject_id, count,as.numeric(xmlAttrs(city)['x']), as.numeric(xmlAttrs(city)['y']), as.numeric(xmlAttrs(city)['group']))
    coord <- rbind(coord, data)
  }
  colnames(coord) <- c("map_id","subject_id","index","x", "y", "group")
  coord
}


coord_1_1 <- get_experiment_coord(map_id=1, subject_id=1, subject_dir_map)
coord_1_2 <- get_experiment_coord(map_id=1, subject_id=2, subject_dir_map)
coord_1_3 <- get_experiment_coord(map_id=1, subject_id=3, subject_dir_map)
coord_2_1 <- get_experiment_coord(map_id=2, subject_id=1, subject_dir_map)
coord_2_2 <- get_experiment_coord(map_id=2, subject_id=2, subject_dir_map)
coord_2_3 <- get_experiment_coord(map_id=2, subject_id=3, subject_dir_map)
coord_3_1 <- get_experiment_coord(map_id=3, subject_id=1, subject_dir_map)
coord_3_2 <- get_experiment_coord(map_id=3, subject_id=2, subject_dir_map)
coord_3_3 <- get_experiment_coord(map_id=3, subject_id=3, subject_dir_map)

coord<-rbind(coord_1_1,coord_1_2,coord_1_3,coord_2_1,coord_2_2,coord_2_3,coord_3_1,coord_3_2,coord_3_3)
coord$group <- as.factor(coord$group)
coord$map_id <- as.character(coord$map_id)
coord$subject_id <- as.character(coord$subject_id)
```

```{r }

hp <- ggplot(coord, aes(x, y)) +
  geom_point(aes(color = group), size = 2) + geom_path()

map_labels <- c("1"="Map 1#", "2"="Map 2#", "3"="Map 3#")
subject_labels <- c("1"="Subject 1#", "2"="Subject 2#", "3"="Subject 3#")

# Histogram of total_bill, divided by sex and smoker
hp + facet_grid(subject_id ~ map_id, labeller=labeller(map_id = map_labels, subject_id = subject_labels))

library(knitr)
sub_table <- experiment_table[experiment_table$map_id %in% 1:3 & experiment_table$subject_id %in% 1:3,]
xtable_sub <- xtabs( real_score ~ subject_id +map_id , sub_table, drop.unused.levels=TRUE)
colnames(xtable_sub)<-c("Map #1","Map #2","Map #3")
rownames(xtable_sub)<-c("Subject #1","Subject #2","Subject #3")

kable(xtable_sub, caption = "Scores for Subject 1:3 on Map 1:3")

xtable_best<-data.frame(map_score[1],map_score[2],map_score[3])
colnames(xtable_best)<-c("Map #1","Map #2","Map #3")
rownames(xtable_best)<-c("Best Score in Theory")

kable(xtable_best, caption = "Best Scores for Map 1:3")

error_ratio <- xtable_sub
xtable_best1<-rbind(xtable_best,xtable_best,xtable_best)
error_ratio2<-(error_ratio-xtable_best1)/xtable_best1
rownames(error_ratio2)<-c("Subject #1","Subject #2","Subject #3")

kable(error_ratio2, caption = "Error Ratios for Subject 1 to 3 on Map 1 to 3")

```

```{r, 2_model_regression}
experiment_table_lm <- experiment_table
experiment_table$map_id <- as.factor(experiment_table$map_id)
experiment_table$block_1_to_6 <- as.factor(experiment_table$block_1_to_6)
experiment_table$subject_id <- as.factor(experiment_table$subject_id)

anomod <- aov(log(err_ratio) ~ subject_id + map_id + block_1_to_6, data=experiment_table)
summary(anomod)

fit.lm <- lm(log(err_ratio) ~ subject_id + map_id + block_1_to_6, data=experiment_table)
summary(fit.lm)
qqnorm(fit.lm$residuals)

#prediction

```

## Classification prediction
```{r}
## boxplot
par(mar=c(4,4,2,4),mfrow=c(1,6))
boxplot(experiment_table[experiment_table$block_1_to_6==1,]$err_ratio,col="seagreen",ylim=c(0,0.8),xlab="block1")
lines(x=c(0.8,1.2),y=c(median(experiment_table[experiment_table$block_1_to_6==1,]$err_ratio),median(experiment_table[experiment_table$block_1_to_6==1,]$err_ratio)),col='red',lwd=2)
boxplot(experiment_table[experiment_table$block_1_to_6==2,]$err_ratio,col="seagreen",ylim=c(0,0.8),xlab="block2")
lines(x=c(0.8,1.2),y=c(median(experiment_table[experiment_table$block_1_to_6==2,]$err_ratio),median(experiment_table[experiment_table$block_1_to_6==2,]$err_ratio)),col='red',lwd=2)
boxplot(experiment_table[experiment_table$block_1_to_6==3,]$err_ratio,col="seagreen",ylim=c(0,0.8),xlab="block3")
lines(x=c(0.8,1.2),y=c(median(experiment_table[experiment_table$block_1_to_6==3,]$err_ratio),median(experiment_table[experiment_table$block_1_to_6==3,]$err_ratio)),col='red',lwd=2)
boxplot(experiment_table[experiment_table$block_1_to_6==4,]$err_ratio,col="seagreen",ylim=c(0,0.8),xlab="block4")
lines(x=c(0.8,1.2),y=c(median(experiment_table[experiment_table$block_1_to_6==4,]$err_ratio),median(experiment_table[experiment_table$block_1_to_6==4,]$err_ratio)),col='red',lwd=2)
boxplot(experiment_table[experiment_table$block_1_to_6==5,]$err_ratio,col="seagreen",ylim=c(0,0.8),xlab="block5")
lines(x=c(0.8,1.2),y=c(median(experiment_table[experiment_table$block_1_to_6==5,]$err_ratio),median(experiment_table[experiment_table$block_1_to_6==5,]$err_ratio)),col='red',lwd=2)
boxplot(experiment_table[experiment_table$block_1_to_6==6,]$err_ratio,col="seagreen",ylim=c(0,0.8),xlab="block6")
lines(x=c(0.8,1.2),y=c(median(experiment_table[experiment_table$block_1_to_6==6,]$err_ratio),median(experiment_table[experiment_table$block_1_to_6==6,]$err_ratio)),col='red',lwd=2)



res <- as.data.frame(cbind(experiment_table$map_id,experiment_table$subject_id,experiment_table$err_ratio))
names(res) <- c("map_id","subject_id","err_ratio")
ggplot(res,aes(x=map_id, y = log(err_ratio),colour=subject_id)) + geom_point()
ggplot(res,aes(x=subject_id, y = log(err_ratio),colour=map_id)) + geom_point()

#train

train_data <- res[which(res$subject_id<22),]
test_data <- res[which(res$subject_id >21),]
train_data$index <- c(1:630)

get_distance <- function(x,y){
  distance <- abs(x-y)
  distance
}
get_knn <- function(k,training_data,test_point){
  my_dist <- lapply(training_data, get_distance, test_point)
  my_dist_sort <- sort(unlist(my_dist),index.return = TRUE)
  my_dist_sort$ix[1:k]
}


get_lable <- function(k,training_data,test_point){
  index <- get_knn(k,training_data,test_point)
  train_data[index,]$map_id
}

get_lable(10,train_data$err_ratio,0.25245273)[1]
# lapply(test_data$err_ratio)
#plot kmeans
autoplot(kmeans(res[,c(1,3)], 30),data=res,label=TRUE, label.size=3, frame=FALSE)
```

